#!/bin/bash
set -e
. "./common-flags"
cd build
cd yaml-cpp-yaml-cpp-0.7.0
[ ! -e build ] || rm -rf build
mkdir -p build
cd build
emcmake cmake .. -DCMAKE_BUILD_TYPE=Release -DYAML_CPP_BUILD_TOOLS=off -DYAML_CPP_BUILD_TESTS=off
emmake make -j$(nproc)
emmake make install
