#!/bin/bash
export CXXFLAGS="-Wno-deprecated-declarations  -DBOOST_NO_EXCEPTIONS"
export LDFLAGS="-sASYNCIFY -s ALLOW_MEMORY_GROWTH=1 -sWASMFS -s EXPORT_ES6=1 -sMODULARIZE=1 -sUSE_ES6_IMPORT_META=0 -sENVIRONMENT=worker --bind -sNO_DYNAMIC_EXECUTION=1"

mkdir -p cmake-build-wasm
cd cmake-build-wasm

emcmake cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TEST=0 -DENABLE_LOGGING=on -DBUILD_STATIC=on 
emmake make -j4 rime_emscripten
