#!/bin/bash
set -e
source ./common-flags
cd build
cd glog-master
[ ! -e build ] || rm -rf build
mkdir -p build
cd build
emcmake cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_UNWIND=off -DWITH_GTEST=off
emmake make -j$(nproc)
emmake make install
